### ISSUE TITLE
Don't require JS Doc @return if there is no return in the function

### ISSUE THREAD

**Issue by webstrap** [styladev/stylaguide#10]
Mostly agreed

valid-jsdoc requireReturn false

That means when your function is returning nothing you have not to add 

@return {void} void

**Comment by mousemke** [comment]
the benefit i see to keeping it is there isnt missing info.  Missing info can lead to assumptions that are not true

**Comment by maciejhirsz** [comment]
The linter prevents you from having missing info - adding a `return` statement to a function that does not have `@return` listed in jsdoc will cause a linter error.

**Comment by mousemke** [comment]
as long as that's the case.  agreed.  I'm against a looser enforcement but like enforcement of a smart, dynamic rule

**Comment by maciejhirsz** [comment]
Closed by #14
