### ISSUE TITLE
comma-dangle always-multiline

### ISSUE THREAD

**Issue by webstrap** [styladev/stylaguide#13]
Mostly agreed on. In multiline array or object definitions there should be a dangling comma ..
Examples: 
var foo = {
    bar: "baz",
    qux: "quux",
};

var foo = {bar: "baz", qux: "quux"};
var arr = [1,2];

var arr = [1,
    2];

var arr = [
    1,
    2,
];
http://eslint.org/docs/rules/comma-dangle

**Comment by mousemke** [comment]
https://medium.com/@nikgraf/why-you-should-enforce-dangling-commas-for-multiline-statements-d034c98e36f8#.ls70dhvk4
