### ISSUE TITLE
Don't enforce parameter description in JS Doc

### ISSUE THREAD

**Issue by webstrap** [styladev/stylaguide#9]
Different opinions

valid-jsdoc = requireParamDescription false

The main reason was that having 

@param {Number} ratio

on the method getImageHeight is already self-describing and you don't add additional value with writing it again behind.

**Comment by eliasliedholm** [comment]
Im fine with this if everyone promises to always remember to add params when its necessary.

Which I highly doubt...

**Comment by maciejhirsz** [comment]
Closed by #14
